format_version: 9
environments:
  default:
    pipelines:
      - example
pipelines:
  example:
    group: example
    materials:
      git:
        git: https://github.com/showerlee/gocd-yaml-config-example.git
    stages:
      - build:
          clean_workspace: yes
          jobs:
            base:
              tasks:
               - exec:
                   command: auto/build-base-image
            app:
              tasks:
               - exec:
                   command: auto/build-base-image

      - release:
          clean_workspace: yes
          jobs:
            base:
              tasks:
                - exec:
                    command: auto/release-base-image
            app:
              tasks:
                - exec:
                    command: auto/release-app-image

      - deploy:
          jobs:
            app:
              tasks:
                - exec:
                    command: auto/deploy
