format_version: 9
environments:
  default:
    pipelines:
      - example
pipelines:
  example:
    group: example
    materials:
      git:
        git: https://github.com/showerlee/gocd-yaml-config-example.git
    stages:
      - build:
          clean_workspace: yes
          jobs:
            Build-base-docker:
              tasks:
               - exec:
                   command: echo "Base image build is complete"
            Build-app-docker:
              tasks:
               - exec:
                   command: echo "App image build is complete"

      - release:
          jobs:
            Release-base-docker:
              tasks:
                - exec:
                    command: echo "Base image release is complete"
            Release-app-docker:
              tasks:
                - exec:
                    command: echo "App image release is complete"

      - deploy:
          jobs:
            Deploy:
              tasks:
                - exec:
                    command: echo "Deployment is complete"
